### PR TITLE
upload: support files over 2^31 bytes

### PR DESCRIPTION
**Pull request by grahamc**
*Description of changes:*

Multiplying offset and blocks as i32 broke on larger images.

Co-authored-by: Cole Helbling <cole.helbling@determinate.systems>

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

---

It would be really better if the interface didn't take signed integers at all, I assume this is Java internals leaking out through the generator.

### CODE REVIEW

**Review by bcressey — APPROVED** [review]
Thanks!

**Comment by grahamc** [comment]
(rebased)

**Review by jpculp — APPROVED** [review]
Thank you for the contribution! Actions and simple 3GB upload/download test passed.

**Comment by cbgbt** [comment]
This looks great, thanks very much!

**Comment by grahamc** [comment]
Thanks!

**Pull request merged**
