### PR TITLE
Update rusoto to 0.47.0

### PR DESCRIPTION
**Pull request by jpculp**
*Description of changes:*

**rusoto_core:** 0.46.0 → 0.47.0 
**rusoto_credential:** 0.46.0 → 0.47.0 
**rusoto_ebs:** 0.46.0 → 0.47.0 
**rusoto_ec2:** 0.46.0 → 0.47.0
**rusoto_signature:** 0.46.0 → 0.47.0

This PR combines #68, #69, #70, #71, and #72, into a single commit.

---

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by webern** [comment]
For this we usually test by pushing and pulling an image. I usually pull one of my bottlerocket snaps and then push it back up.

**Comment by jpculp** [comment]
Tested by downloading a snapshot and re-uploading, per @webern.

**Review by webern — APPROVED** [review]

**Comment by jpculp** [comment]
Also tested by uploading an image, downloading the snapshot, and comparing the `sha512sum` to the original image.

**Comment by jpculp** [comment]
Re-based to run new `check-licenses` check.

**Review by tjkirch — APPROVED** [review]

**Pull request merged**
