### PR TITLE
Upgrade SNAFU to 0.7

### PR DESCRIPTION
**Pull request by shepmaster**
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by shepmaster** [comment]
Looks like some formatting changes (as the selector names are a bit longer now) I can run rustfmt and force-push.

**Review by jpculp — APPROVED** [review]
This is great! Thank you for submitting this!

I did a quick upload/download test and everything looked OK.

**Review by webern — APPROVED** [review]
Thank you for pro-actively updating your clients!

**Comment by shepmaster** [comment]
> pro-actively updating your clients

It's a mutual thing — I used your crate (and others!) via [a crater-like tool](https://github.com/shepmaster/mini-crater) to create and test the [auto-upgrade tool](https://github.com/shepmaster/snafu-upgrade-assistant), so then it was easy to submit the PR. 😉

**Review by cbgbt — APPROVED** [review]
It was really nice of you to send these update PRs. Thank you!

**Review by bcressey — APPROVED** [review]
❤️

**Comment by shepmaster** [comment]
Thanks for using SNAFU!

**Pull request merged**
